xcvrd: sff_mgr missing log_info leading to crashes
The logger object may be different based on subsystem but not all
have the same log callbacks leading to errors in SffLogger:
```
2025 Jun 26 10:25:14.640757 dvc140 ERR pmon#xcvrd[120]:     self.logger.log_info("subscribing to port_tbl {} - {} DB of namespace {} ".format(
2025 Jun 26 10:25:14.640793 dvc140 ERR pmon#xcvrd[120]:     ^^^^^^^^^^^^^^^^^^^^
2025 Jun 26 10:25:14.640793 dvc140 ERR pmon#xcvrd[120]: AttributeError: 'SffLoggerForPortUpdateEvent' object has no attribute 'log_info'
```

This patch adds log_info to Sff.

Signed-off-by: Brad House <bhouse@nexthop.ai>